### ISSUE TITLE
Add a way to tag models with versions for easier pulling

### ISSUE THREAD

**Issue by sachinshelke** [cloud-annotations/cloud-annotations#117]
Whenever new model training and loaded using typescript (either in Angular or react project), model version return `undefined`. 
**Can it be possible to defined version to model after training?**

Also tried to deploy using `bx ml deploy [model_id] [name_to_the_deployment]`, it won't work return error that `Requested object could not be found.`.

**Comment by bourdakos1** [comment]
I’m not sure what you’re trying to achieve, could you explain a bit further? Are you trying to deploy the trained model as an API?

**Comment by sachinshelke** [comment]
Sorry My Bad, I mixed up two things in one.

1. Actually,  I wanted to re-download model, if model new model uploaded on server without changing any code. But @tensorflow/tfjs does not re-download it if new model available on server.
> That's why I think model versioning required.



2. Yes, I'm trying to deploy trained model to IBM Cloud using cli. But it throw error as mentioned in above description. (Not priority - Just tried to deploy)

**Comment by bourdakos1** [comment]
Ahh gotcha

re-download a model on updates:
There's a few ways you could probably achieve this (none out-of-the-box (yet)). One way is query Watson Machine Learning which would give you a list of all your training runs, you could find the most recent one with a specific name and download it. 
I finally put together a small sdk for this project, so I can try and integrate this maybe? The only downside would be that you would need to store your watson machine learning and object storage credentials on the frontend 

deploy trained model to IBM Cloud:
I haven't tried this yet, but I can look into it

**Comment by sachinshelke** [comment]
Thanks,
I tried with IBM ML CLI `bx ml models download [model-id]` but unfortunately it responded with error `Requested object could not be found.`
I will also try to find out another way.

**Comment by bourdakos1** [comment]
Oh I think you need to add the model to WML first, cacli doesn’t do that automatically. I’ll have to do some research this week

**Comment by bourdakos1** [comment]
I did a bit of digging and it looks like you need to store the model first, which gives you a different model-id, which you can you to download the model

You can follow here https://github.com/cloud-annotations/training/issues/45

**Comment by bourdakos1** [comment]
@sachinshelke I’m thinking of adding a `loadFromObjectStorage` method that can pull a model from object storage instead of having to download it and add it to your project manually.

I’m not sure how I want to handle versioning. I’m thinking that you would just give it your bucket information and by default it would pull the newest version. And possibly if you pass a date it will pull the latest model up to that date?

I could also generate some sort of metadata file so you could pass a version or tag when training. Then you would pass that information when pulling the model, like “v1.2.3” or “staging” or whatever you tagged it with

Does that make sense to you?
